### PR TITLE
Extend the Device State API to support Device Shadow

### PR DESCRIPTION
**Pull request by kjaskiewiczz**
Ticket: https://tracker.mender.io/browse/MEN-5448

### CODE REVIEW

**Comment by tranchitella** [comment]
To be tested with: https://github.com/mendersoftware/integration/pull/2118

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr integration/2118 --fast

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr integration/2118 --fast

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr integration/2118 --fast

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
